
import Form from "../components/form";
import Head from "next/head";
import LayoutUser from "@/layouts/layoutUser";

const Contacts = () => {

    return <>
        <Head>
            <title>Contacts</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <LayoutUser>
            <div className="contacts__section">
                <Form type={"message"}/>
            </div>
        </LayoutUser>
    </>
}

export default Contacts;