import Head from "next/head";
import Form from "../components/form";
import LayoutUser from "@/layouts/layoutUser";

const Login = () => {


    return <>
        <Head>
            <title>Login</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <LayoutUser>
        <div className="login__div">
            <Form type="login"/>
        </div>
        </LayoutUser>    
    </>
}

export default Login;